/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a usage statistics report through the Nextcloud OCS API
         * @description This endpoint has the same Protocol v1 request semantics as the plain JSON endpoint, but wraps the response using the standard Nextcloud OCS envelope.
         */
        post: operations["ocs_report-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index.php/apps/usage_statistics_server/api/{apiVersion}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a usage statistics report as plain Protocol v1 JSON
         * @description Stores one validated report for one application installation and reporting period. Repeating an already accepted report with the same schema version is idempotent.
         */
        post: operations["report-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "ocs_report-create": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Usage statistics protocol version
                     */
                    protocolVersion: number;
                    /** @description Stable application identifier */
                    application: string;
                    /** @description Stable pseudonymous installation identifier */
                    installationId: string;
                    /**
                     * Format: int64
                     * @description Registered application schema version
                     */
                    schemaVersion: number;
                    /** @description RFC3339 reporting period, start inclusive and end exclusive */
                    period: {
                        start: string;
                        end: string;
                    };
                    /** @description Aggregate metric values */
                    metrics: {
                        category: string;
                        key: string;
                        type: string;
                        value: string | number | boolean;
                    }[];
                };
            };
        };
        responses: {
            /** @description Report accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                status: string;
                            };
                        };
                    };
                };
            };
            /** @description Invalid report */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Conflicting report for the reporting period */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "report-create": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Usage statistics protocol version
                     */
                    protocolVersion: number;
                    /** @description Stable application identifier */
                    application: string;
                    /** @description Stable pseudonymous installation identifier */
                    installationId: string;
                    /**
                     * Format: int64
                     * @description Registered application schema version
                     */
                    schemaVersion: number;
                    /** @description RFC3339 reporting period, start inclusive and end exclusive */
                    period: {
                        start: string;
                        end: string;
                    };
                    /** @description Aggregate metric values */
                    metrics: {
                        category: string;
                        key: string;
                        type: string;
                        value: string | number | boolean;
                    }[];
                };
            };
        };
        responses: {
            /** @description Report accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
            /** @description Invalid report */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message: string;
                    };
                };
            };
            /** @description Conflicting report for the reporting period */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message: string;
                    };
                };
            };
        };
    };
}
