/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an application metric schema
         * @description This endpoint requires admin access
         */
        post: operations["schema-create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/schemas/{application}/{schemaVersion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one registered application metric schema
         * @description This endpoint requires admin access
         */
        get: operations["schema-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get usage statistics server settings
         * @description This endpoint requires admin access
         */
        get: operations["settings-get"];
        /**
         * Update usage statistics server settings
         * @description This endpoint requires admin access
         */
        put: operations["settings-update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/applications/{application}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get application usage statistics summary
         * @description This endpoint requires admin access
         */
        get: operations["statistics-summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/applications/{application}/metrics/{category}/{key}/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current distribution for a metric
         * @description This endpoint requires admin access
         */
        get: operations["statistics-distribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/applications/{application}/metrics/{category}/{key}/numerical": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current numerical evaluation for a metric
         * @description This endpoint requires admin access
         */
        get: operations["statistics-numerical"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ocs/v2.php/apps/usage_statistics_server/api/{apiVersion}/admin/applications/{application}/metrics/{category}/{key}/numerical/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical numerical evaluation for a metric
         * @description This endpoint requires admin access
         */
        get: operations["statistics-numerical-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        OCSMeta: {
            status: string;
            statuscode: number;
            message?: string;
            totalitems?: string;
            itemsperpage?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "schema-create": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Stable application identifier */
                    application: string;
                    /**
                     * Format: int64
                     * @description Immutable schema version
                     */
                    schemaVersion: number;
                    /** @description Metric definitions */
                    metrics: {
                        category: string;
                        key: string;
                        type: string;
                        kind: string;
                        aggregation: string;
                        description: string;
                        required: boolean;
                    }[];
                };
            };
        };
        responses: {
            /** @description Schema was already registered with the same definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                application: string;
                                /** Format: int64 */
                                schemaVersion: number;
                                status: string;
                            };
                        };
                    };
                };
            };
            /** @description Schema registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                application: string;
                                /** Format: int64 */
                                schemaVersion: number;
                                status: string;
                            };
                        };
                    };
                };
            };
            /** @description Invalid schema definition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Schema version already exists with another definition */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "schema-get": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Stable application identifier */
                application: string;
                /** @description Schema version */
                schemaVersion: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered schema definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                [key: string]: Record<string, never>;
                            };
                        };
                    };
                };
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "settings-get": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current server settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                /** Format: int64 */
                                retentionDays: number;
                                /** Format: int64 */
                                minimumRetentionDays: number;
                                /** Format: int64 */
                                maximumRetentionDays: number;
                            };
                        };
                    };
                };
            };
        };
    };
    "settings-update": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: int64
                     * @description Number of days to retain reports
                     */
                    retentionDays: number;
                };
            };
        };
        responses: {
            /** @description Server settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                /** Format: int64 */
                                retentionDays: number;
                            };
                        };
                    };
                };
            };
            /** @description Invalid retention value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "statistics-summary": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Stable application identifier */
                application: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application usage statistics summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                application: string;
                                /** Format: int64 */
                                activeWindowDays: number;
                                /** Format: int64 */
                                activeInstallations: number;
                            };
                        };
                    };
                };
            };
        };
    };
    "statistics-distribution": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Stable application identifier */
                application: string;
                /** @description Metric category */
                category: string;
                /** @description Metric key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current metric distribution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                application: string;
                                category: string;
                                key: string;
                                values: {
                                    value: Record<string, never>;
                                    /** Format: int64 */
                                    count: number;
                                }[];
                            };
                        };
                    };
                };
            };
            /** @description Metric does not support distribution aggregation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Metric is not registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "statistics-numerical": {
        parameters: {
            query?: never;
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Stable application identifier */
                application: string;
                /** @description Metric category */
                category: string;
                /** @description Metric key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current numerical metric evaluation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                application: string;
                                category: string;
                                key: string;
                                statistics: {
                                    /** Format: int64 */
                                    count: number;
                                    /** Format: double */
                                    average: number | null;
                                    /** Format: double */
                                    min: number | null;
                                    /** Format: double */
                                    max: number | null;
                                    /** Format: double */
                                    total: number | null;
                                };
                            };
                        };
                    };
                };
            };
            /** @description Metric does not support numerical aggregation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Metric is not registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
    "statistics-numerical-history": {
        parameters: {
            query?: {
                /** @description Optional RFC3339 lower bound */
                from?: string;
                /** @description Optional RFC3339 upper bound */
                to?: string;
            };
            header: {
                /** @description Required to be true for the API request to pass */
                "OCS-APIRequest": boolean;
            };
            path: {
                apiVersion: "v1";
                /** @description Stable application identifier */
                application: string;
                /** @description Metric category */
                category: string;
                /** @description Metric key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historical numerical metric evaluation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                application: string;
                                category: string;
                                key: string;
                                from: string;
                                to: string;
                                periods: {
                                    periodStart: string;
                                    periodEnd: string;
                                    /** Format: int64 */
                                    count: number;
                                    /** Format: double */
                                    average: number | null;
                                    /** Format: double */
                                    min: number | null;
                                    /** Format: double */
                                    max: number | null;
                                    /** Format: double */
                                    total: number | null;
                                }[];
                            };
                        };
                    };
                };
            };
            /** @description Invalid date range or metric aggregation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
            /** @description Metric is not registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ocs: {
                            meta: components["schemas"]["OCSMeta"];
                            data: {
                                error: string;
                                message: string;
                            };
                        };
                    };
                };
            };
        };
    };
}
