services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  Doctrine\DBAL\Connection:
    factory: ['Doctrine\DBAL\DriverManager', 'getConnection']
    arguments:
      - { url: '%env(resolve:DATABASE_URL)%' }
