name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.3'
          coverage: none
      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
      - run: composer validate --strict
      - run: composer lint

  nextcloud:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server-version:
          - stable35
          - master
    steps:
      - name: Checkout Nextcloud
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: nextcloud/server
          ref: ${{ matrix.server-version }}
          submodules: true

      - name: Checkout app
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          path: apps/usage_statistics_server

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.3'
          coverage: none
          extensions: ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, sqlite3, pdo_sqlite, xmlreader, xmlwriter, zip, zlib

      - name: Install app dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          working-directory: apps/usage_statistics_server

      - name: Install Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --database=sqlite --admin-user=admin --admin-pass=admin
          ./occ app:enable --force usage_statistics_server

      - name: Run unit tests
        working-directory: apps/usage_statistics_server
        run: composer test:unit
