# This workflow is based on the Nextcloud organization workflow template.
#
# https://github.com/nextcloud/.github
# SPDX-FileCopyrightText: 2022-2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit PostgreSQL

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: phpunit-pgsql-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.sparse-matrix }}
    steps:
      - name: Checkout app
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@cd0211ffcef1065e2020cd579e4843b8746e7a58 # v1.3.3

  phpunit-pgsql:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    env:
      APP_NAME: usage_statistics_server
    name: PostgreSQL PHP ${{ matrix.php-versions }} Nextcloud ${{ matrix.server-versions }}
    services:
      postgres:
        image: ghcr.io/nextcloud/continuous-integration-postgres-16:latest
        ports:
          - 4444:5432/tcp
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: nextcloud
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5
    steps:
      - name: Checkout server
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
      - name: Checkout app
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          path: apps/${{ env.APP_NAME }}
      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, pgsql, pdo_pgsql
          coverage: none
          ini-file: development
          ini-values: disable_functions=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install app dependencies
        working-directory: apps/${{ env.APP_NAME }}
        run: |
          composer remove nextcloud/ocp --dev --no-scripts
          composer install
      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=pgsql --database-name=nextcloud --database-host=127.0.0.1 --database-port=4444 --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          ./occ --version
          ./occ app:enable --force ${{ env.APP_NAME }}
      - name: Run PHPUnit suites
        working-directory: apps/${{ env.APP_NAME }}
        run: composer run test:php
      - name: Print logs
        if: always()
        run: cat data/nextcloud.log || true
