# SPDX-FileCopyrightText: 2026 Vitor Mattos
# SPDX-License-Identifier: AGPL-3.0-or-later

name: PHPUnit SQLite

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: phpunit-sqlite-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.sparse-matrix }}

    steps:
      - name: Checkout app
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@8a7bac6300b2f0f3100088b297995a229558ddba # v1.3.2

  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/phpunit*'
              - 'appinfo/**'
              - 'lib/**'
              - 'tests/**'
              - 'composer.json'
              - 'composer.lock'

  phpunit-sqlite:
    runs-on: ubuntu-latest
    needs: [changes, matrix]
    if: needs.changes.outputs.src != 'false'

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}

    env:
      APP_NAME: usage_statistics_server

    name: SQLite PHP ${{ matrix.php-versions }} Nextcloud ${{ matrix.server-versions }}

    steps:
      - name: Checkout server
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite
          coverage: none
          ini-file: development
          ini-values: disable_functions=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install app dependencies
        working-directory: apps/${{ env.APP_NAME }}
        run: |
          composer remove nextcloud/ocp --dev --no-scripts
          composer install

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install \
            --verbose \
            --database=sqlite \
            --database-name=nextcloud \
            --admin-user admin \
            --admin-pass admin
          ./occ --version
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: Run PHPUnit suites
        working-directory: apps/${{ env.APP_NAME }}
        run: composer run test:php

      - name: Print logs
        if: always()
        run: cat data/nextcloud.log || true

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [changes, phpunit-sqlite]
    if: always()

    name: phpunit-sqlite-summary

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && needs.phpunit-sqlite.result != 'success' }}; then exit 1; fi
