# This workflow is based on the Nextcloud organization workflow template.
#
# https://github.com/nextcloud/.github
# SPDX-FileCopyrightText: 2023-2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit MariaDB

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: phpunit-mariadb-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.sparse-matrix }}
    steps:
      - name: Checkout app
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@cd0211ffcef1065e2020cd579e4843b8746e7a58 # v1.3.3
        with:
          matrix: '{"mariadb-versions": ["10.6", "11.4"]}'

  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/phpunit*'
              - 'appinfo/**'
              - 'lib/**'
              - 'tests/**'
              - 'composer.json'
              - 'composer.lock'

  phpunit-mariadb:
    runs-on: ubuntu-latest
    needs: [changes, matrix]
    if: needs.changes.outputs.src != 'false'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    env:
      APP_NAME: usage_statistics_server
    name: MariaDB ${{ matrix.mariadb-versions }} PHP ${{ matrix.php-versions }} Nextcloud ${{ matrix.server-versions }}
    services:
      mariadb:
        image: ghcr.io/nextcloud/continuous-integration-mariadb-${{ matrix.mariadb-versions }}:latest
        ports:
          - 4444:3306/tcp
        env:
          MARIADB_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mariadb-admin ping" --health-interval 5s --health-timeout 2s --health-retries 10
    steps:
      - name: Checkout server
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
      - name: Checkout app
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          path: apps/${{ env.APP_NAME }}
      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, mysql, pdo_mysql
          coverage: none
          ini-file: development
          ini-values: disable_functions=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable ONLY_FULL_GROUP_BY
        run: |
          echo "SET GLOBAL sql_mode=(SELECT CONCAT(@@sql_mode,',ONLY_FULL_GROUP_BY'));" | mysql -h 127.0.0.1 -P 4444 -u root -prootpassword
          echo 'SELECT @@sql_mode;' | mysql -h 127.0.0.1 -P 4444 -u root -prootpassword
      - name: Install app dependencies
        working-directory: apps/${{ env.APP_NAME }}
        run: |
          composer remove nextcloud/ocp --dev --no-scripts
          composer install
      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=mysql --database-name=nextcloud --database-host=127.0.0.1 --database-port=4444 --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          ./occ --version
          ./occ app:enable --force ${{ env.APP_NAME }}
      - name: Run PHPUnit suites
        working-directory: apps/${{ env.APP_NAME }}
        run: composer run test:php
      - name: Print logs
        if: always()
        run: cat data/nextcloud.log || true

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [changes, phpunit-mariadb]
    if: always()
    name: phpunit-mariadb-summary
    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && needs.phpunit-mariadb.result != 'success' }}; then exit 1; fi
